#include "Z80Core.h"

CZ80Core::Z80OpcodeTable CZ80Core::FDCB_Opcodes = {
{
	{ &CZ80Core::LD_B_RLC_off_IX_IY_d   , "LD B,RLC (IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RLC_off_IX_IY_d   , "LD C,RLC (IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RLC_off_IX_IY_d   , "LD D,RLC (IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RLC_off_IX_IY_d   , "LD E,RLC (IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RLC_off_IX_IY_d   , "LD H,RLC (IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RLC_off_IX_IY_d   , "LD L,RLC (IY+0%02Xh)" },
	{ &CZ80Core::RLC_off_IX_IY_d        , "RLC (IY+0%02Xh)"	  },
	{ &CZ80Core::LD_A_RLC_off_IX_IY_d   , "LD A,RLC (IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RRC_off_IX_IY_d   , "LD B,RRC (IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RRC_off_IX_IY_d   , "LD C,RRC (IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RRC_off_IX_IY_d   , "LD D,RRC (IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RRC_off_IX_IY_d   , "LD E,RRC (IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RRC_off_IX_IY_d   , "LD H,RRC (IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RRC_off_IX_IY_d   , "LD L,RRC (IY+0%02Xh)" },
	{ &CZ80Core::RRC_off_IX_IY_d        , "RRC (IY+0%02Xh)"	  },
	{ &CZ80Core::LD_A_RRC_off_IX_IY_d   , "LD A,RRC (IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RL_off_IX_IY_d    , "LD B,RL (IY+0%02Xh)"  },
	{ &CZ80Core::LD_C_RL_off_IX_IY_d    , "LD C,RL (IY+0%02Xh)"  },
	{ &CZ80Core::LD_D_RL_off_IX_IY_d    , "LD D,RL (IY+0%02Xh)"  },
	{ &CZ80Core::LD_E_RL_off_IX_IY_d    , "LD E,RL (IY+0%02Xh)"  },
	{ &CZ80Core::LD_H_RL_off_IX_IY_d    , "LD H,RL (IY+0%02Xh)"  },
	{ &CZ80Core::LD_L_RL_off_IX_IY_d    , "LD L,RL (IY+0%02Xh)"  },
	{ &CZ80Core::RL_off_IX_IY_d         , "RL (IY+0%02Xh)"       },
	{ &CZ80Core::LD_A_RL_off_IX_IY_d    , "LD A,RL (IY+0%02Xh)"  },
	{ &CZ80Core::LD_B_RR_off_IX_IY_d    , "LD B,RR (IY+0%02Xh)"  },
	{ &CZ80Core::LD_C_RR_off_IX_IY_d    , "LD C,RR (IY+0%02Xh)"  },
	{ &CZ80Core::LD_D_RR_off_IX_IY_d    , "LD D,RR (IY+0%02Xh)"  },
	{ &CZ80Core::LD_E_RR_off_IX_IY_d    , "LD E,RR (IY+0%02Xh)"  },
	{ &CZ80Core::LD_H_RR_off_IX_IY_d    , "LD H,RR (IY+0%02Xh)"  },
	{ &CZ80Core::LD_L_RR_off_IX_IY_d    , "LD L,RR (IY+0%02Xh)"  },
	{ &CZ80Core::RR_off_IX_IY_d         , "RR (IY+0%02Xh)"       },
	{ &CZ80Core::LD_A_RR_off_IX_IY_d    , "LD A,RR (IY+0%02Xh)"  },
	{ &CZ80Core::LD_B_SLA_off_IX_IY_d   , "LD B,SLA (IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SLA_off_IX_IY_d   , "LD C,SLA (IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SLA_off_IX_IY_d   , "LD D,SLA (IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SLA_off_IX_IY_d   , "LD E,SLA (IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SLA_off_IX_IY_d   , "LD H,SLA (IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SLA_off_IX_IY_d   , "LD L,SLA (IY+0%02Xh)" },
	{ &CZ80Core::SLA_off_IX_IY_d        , "SLA (IY+0%02Xh)"      },
	{ &CZ80Core::LD_A_SLA_off_IX_IY_d   , "LD A,SLA (IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SRA_off_IX_IY_d   , "LD B,SRA (IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SRA_off_IX_IY_d   , "LD C,SRA (IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SRA_off_IX_IY_d   , "LD D,SRA (IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SRA_off_IX_IY_d   , "LD E,SRA (IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SRA_off_IX_IY_d   , "LD H,SRA (IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SRA_off_IX_IY_d   , "LD L,SRA (IY+0%02Xh)" },
	{ &CZ80Core::SRA_off_IX_IY_d        , "SRA (IY+0%02Xh)"      },
	{ &CZ80Core::LD_A_SRA_off_IX_IY_d   , "LD A,SRA (IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SLL_off_IX_IY_d   , "LD B,SLL (IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SLL_off_IX_IY_d   , "LD C,SLL (IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SLL_off_IX_IY_d   , "LD D,SLL (IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SLL_off_IX_IY_d   , "LD E,SLL (IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SLL_off_IX_IY_d   , "LD H,SLL (IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SLL_off_IX_IY_d   , "LD L,SLL (IY+0%02Xh)" },
	{ &CZ80Core::SLL_off_IX_IY_d        , "SLL (IY+0%02Xh)"      },
	{ &CZ80Core::LD_A_SLL_off_IX_IY_d   , "LD A,SLL (IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SRL_off_IX_IY_d   , "LD B,SRL (IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SRL_off_IX_IY_d   , "LD C,SRL (IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SRL_off_IX_IY_d   , "LD D,SRL (IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SRL_off_IX_IY_d   , "LD E,SRL (IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SRL_off_IX_IY_d   , "LD H,SRL (IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SRL_off_IX_IY_d   , "LD L,SRL (IY+0%02Xh)" },
	{ &CZ80Core::SRL_off_IX_IY_d        , "SRL (IY+0%02Xh)"      },
	{ &CZ80Core::LD_A_SRL_off_IX_IY_d   , "LD A,SRL (IY+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IY+0%02Xh)"    },
	{ &CZ80Core::LD_B_RES_0_off_IX_IY_d , "LD B,RES 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_0_off_IX_IY_d , "LD C,RES 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_0_off_IX_IY_d , "LD D,RES 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_0_off_IX_IY_d , "LD E,RES 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_0_off_IX_IY_d , "LD H,RES 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_0_off_IX_IY_d , "LD L,RES 0,(IY+0%02Xh)" },
	{ &CZ80Core::RES_0_off_IX_IY_d      , "RES 0,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_0_off_IX_IY_d , "LD A,RES 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_1_off_IX_IY_d , "LD B,RES 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_1_off_IX_IY_d , "LD C,RES 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_1_off_IX_IY_d , "LD D,RES 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_1_off_IX_IY_d , "LD E,RES 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_1_off_IX_IY_d , "LD H,RES 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_1_off_IX_IY_d , "LD L,RES 1,(IY+0%02Xh)" },
	{ &CZ80Core::RES_1_off_IX_IY_d      , "RES 1,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_1_off_IX_IY_d , "LD A,RES 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_2_off_IX_IY_d , "LD B,RES 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_2_off_IX_IY_d , "LD C,RES 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_2_off_IX_IY_d , "LD D,RES 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_2_off_IX_IY_d , "LD E,RES 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_2_off_IX_IY_d , "LD H,RES 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_2_off_IX_IY_d , "LD L,RES 2,(IY+0%02Xh)" },
	{ &CZ80Core::RES_2_off_IX_IY_d      , "RES 2,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_2_off_IX_IY_d , "LD A,RES 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_3_off_IX_IY_d , "LD B,RES 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_3_off_IX_IY_d , "LD C,RES 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_3_off_IX_IY_d , "LD D,RES 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_3_off_IX_IY_d , "LD E,RES 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_3_off_IX_IY_d , "LD H,RES 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_3_off_IX_IY_d , "LD L,RES 3,(IY+0%02Xh)" },
	{ &CZ80Core::RES_3_off_IX_IY_d      , "RES 3,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_3_off_IX_IY_d , "LD A,RES 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_4_off_IX_IY_d , "LD B,RES 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_4_off_IX_IY_d , "LD C,RES 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_4_off_IX_IY_d , "LD D,RES 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_4_off_IX_IY_d , "LD E,RES 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_4_off_IX_IY_d , "LD H,RES 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_4_off_IX_IY_d , "LD L,RES 4,(IY+0%02Xh)" },
	{ &CZ80Core::RES_4_off_IX_IY_d      , "RES 4,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_4_off_IX_IY_d , "LD A,RES 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_5_off_IX_IY_d , "LD B,RES 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_5_off_IX_IY_d , "LD C,RES 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_5_off_IX_IY_d , "LD D,RES 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_5_off_IX_IY_d , "LD E,RES 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_5_off_IX_IY_d , "LD H,RES 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_5_off_IX_IY_d , "LD L,RES 5,(IY+0%02Xh)" },
	{ &CZ80Core::RES_5_off_IX_IY_d      , "RES 5,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_5_off_IX_IY_d , "LD A,RES 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_6_off_IX_IY_d , "LD B,RES 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_6_off_IX_IY_d , "LD C,RES 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_6_off_IX_IY_d , "LD D,RES 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_6_off_IX_IY_d , "LD E,RES 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_6_off_IX_IY_d , "LD H,RES 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_6_off_IX_IY_d , "LD L,RES 6,(IY+0%02Xh)" },
	{ &CZ80Core::RES_6_off_IX_IY_d      , "RES 6,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_6_off_IX_IY_d , "LD A,RES 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_7_off_IX_IY_d , "LD B,RES 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_7_off_IX_IY_d , "LD C,RES 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_7_off_IX_IY_d , "LD D,RES 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_7_off_IX_IY_d , "LD E,RES 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_7_off_IX_IY_d , "LD H,RES 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_7_off_IX_IY_d , "LD L,RES 7,(IY+0%02Xh)" },
	{ &CZ80Core::RES_7_off_IX_IY_d      , "RES 7,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_RES_7_off_IX_IY_d , "LD A,RES 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_0_off_IX_IY_d , "LD B,SET 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_0_off_IX_IY_d , "LD C,SET 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_0_off_IX_IY_d , "LD D,SET 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_0_off_IX_IY_d , "LD E,SET 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_0_off_IX_IY_d , "LD H,SET 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_0_off_IX_IY_d , "LD L,SET 0,(IY+0%02Xh)" },
	{ &CZ80Core::SET_0_off_IX_IY_d      , "SET 0,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_0_off_IX_IY_d , "LD A,SET 0,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_1_off_IX_IY_d , "LD B,SET 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_1_off_IX_IY_d , "LD C,SET 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_1_off_IX_IY_d , "LD D,SET 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_1_off_IX_IY_d , "LD E,SET 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_1_off_IX_IY_d , "LD H,SET 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_1_off_IX_IY_d , "LD L,SET 1,(IY+0%02Xh)" },
	{ &CZ80Core::SET_1_off_IX_IY_d      , "SET 1,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_1_off_IX_IY_d , "LD A,SET 1,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_2_off_IX_IY_d , "LD B,SET 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_2_off_IX_IY_d , "LD C,SET 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_2_off_IX_IY_d , "LD D,SET 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_2_off_IX_IY_d , "LD E,SET 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_2_off_IX_IY_d , "LD H,SET 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_2_off_IX_IY_d , "LD L,SET 2,(IY+0%02Xh)" },
	{ &CZ80Core::SET_2_off_IX_IY_d      , "SET 2,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_2_off_IX_IY_d , "LD A,SET 2,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_3_off_IX_IY_d , "LD B,SET 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_3_off_IX_IY_d , "LD C,SET 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_3_off_IX_IY_d , "LD D,SET 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_3_off_IX_IY_d , "LD E,SET 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_3_off_IX_IY_d , "LD H,SET 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_3_off_IX_IY_d , "LD L,SET 3,(IY+0%02Xh)" },
	{ &CZ80Core::SET_3_off_IX_IY_d      , "SET 3,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_3_off_IX_IY_d , "LD A,SET 3,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_4_off_IX_IY_d , "LD B,SET 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_4_off_IX_IY_d , "LD C,SET 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_4_off_IX_IY_d , "LD D,SET 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_4_off_IX_IY_d , "LD E,SET 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_4_off_IX_IY_d , "LD H,SET 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_4_off_IX_IY_d , "LD L,SET 4,(IY+0%02Xh)" },
	{ &CZ80Core::SET_4_off_IX_IY_d      , "SET 4,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_4_off_IX_IY_d , "LD A,SET 4,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_5_off_IX_IY_d , "LD B,SET 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_5_off_IX_IY_d , "LD C,SET 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_5_off_IX_IY_d , "LD D,SET 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_5_off_IX_IY_d , "LD E,SET 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_5_off_IX_IY_d , "LD H,SET 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_5_off_IX_IY_d , "LD L,SET 5,(IY+0%02Xh)" },
	{ &CZ80Core::SET_5_off_IX_IY_d      , "SET 5,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_5_off_IX_IY_d , "LD A,SET 5,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_6_off_IX_IY_d , "LD B,SET 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_6_off_IX_IY_d , "LD C,SET 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_6_off_IX_IY_d , "LD D,SET 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_6_off_IX_IY_d , "LD E,SET 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_6_off_IX_IY_d , "LD H,SET 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_6_off_IX_IY_d , "LD L,SET 6,(IY+0%02Xh)" },
	{ &CZ80Core::SET_6_off_IX_IY_d      , "SET 6,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_6_off_IX_IY_d , "LD A,SET 6,(IY+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_7_off_IX_IY_d , "LD B,SET 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_7_off_IX_IY_d , "LD C,SET 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_7_off_IX_IY_d , "LD D,SET 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_7_off_IX_IY_d , "LD E,SET 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_7_off_IX_IY_d , "LD H,SET 7,(IY+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_7_off_IX_IY_d , "LD L,SET 7,(IY+0%02Xh)" },
	{ &CZ80Core::SET_7_off_IX_IY_d      , "SET 7,(IY+0%02Xh)"		},
	{ &CZ80Core::LD_A_SET_7_off_IX_IY_d , "LD A,SET 7,(IY+0%02Xh)" }
} };

CZ80Core::Z80OpcodeTable CZ80Core::CB_Opcodes = {
{
	{ &CZ80Core::RLC_B               , "RLC B"             },
	{ &CZ80Core::RLC_C               , "RLC C"             },
	{ &CZ80Core::RLC_D               , "RLC D"             },
	{ &CZ80Core::RLC_E               , "RLC E"             },
	{ &CZ80Core::RLC_H               , "RLC H"             },
	{ &CZ80Core::RLC_L               , "RLC L"             },
	{ &CZ80Core::RLC_off_HL          , "RLC (HL)"          },
	{ &CZ80Core::RLC_A               , "RLC A"             },
	{ &CZ80Core::RRC_B               , "RRC B"             },
	{ &CZ80Core::RRC_C               , "RRC C"             },
	{ &CZ80Core::RRC_D               , "RRC D"             },
	{ &CZ80Core::RRC_E               , "RRC E"             },
	{ &CZ80Core::RRC_H               , "RRC H"             },
	{ &CZ80Core::RRC_L               , "RRC L"             },
	{ &CZ80Core::RRC_off_HL          , "RRC (HL)"          },
	{ &CZ80Core::RRC_A               , "RRC A"             },
	{ &CZ80Core::RL_B                , "RL B"              },
	{ &CZ80Core::RL_C                , "RL C"              },
	{ &CZ80Core::RL_D                , "RL D"              },
	{ &CZ80Core::RL_E                , "RL E"              },
	{ &CZ80Core::RL_H                , "RL H"              },
	{ &CZ80Core::RL_L                , "RL L"              },
	{ &CZ80Core::RL_off_HL           , "RL (HL)"           },
	{ &CZ80Core::RL_A                , "RL A"              },
	{ &CZ80Core::RR_B                , "RR B"              },
	{ &CZ80Core::RR_C                , "RR C"              },
	{ &CZ80Core::RR_D                , "RR D"              },
	{ &CZ80Core::RR_E                , "RR E"              },
	{ &CZ80Core::RR_H                , "RR H"              },
	{ &CZ80Core::RR_L                , "RR L"              },
	{ &CZ80Core::RR_off_HL           , "RR (HL)"           },
	{ &CZ80Core::RR_A                , "RR A"              },
	{ &CZ80Core::SLA_B               , "SLA B"             },
	{ &CZ80Core::SLA_C               , "SLA C"             },
	{ &CZ80Core::SLA_D               , "SLA D"             },
	{ &CZ80Core::SLA_E               , "SLA E"             },
	{ &CZ80Core::SLA_H               , "SLA H"             },
	{ &CZ80Core::SLA_L               , "SLA L"             },
	{ &CZ80Core::SLA_off_HL          , "SLA (HL)"          },
	{ &CZ80Core::SLA_A               , "SLA A"             },
	{ &CZ80Core::SRA_B               , "SRA B"             },
	{ &CZ80Core::SRA_C               , "SRA C"             },
	{ &CZ80Core::SRA_D               , "SRA D"             },
	{ &CZ80Core::SRA_E               , "SRA E"             },
	{ &CZ80Core::SRA_H               , "SRA H"             },
	{ &CZ80Core::SRA_L               , "SRA L"             },
	{ &CZ80Core::SRA_off_HL          , "SRA (HL)"          },
	{ &CZ80Core::SRA_A               , "SRA A"             },
	{ &CZ80Core::SLL_B               , "SLL B"             },
	{ &CZ80Core::SLL_C               , "SLL C"             },
	{ &CZ80Core::SLL_D               , "SLL D"             },
	{ &CZ80Core::SLL_E               , "SLL E"             },
	{ &CZ80Core::SLL_H               , "SLL H"             },
	{ &CZ80Core::SLL_L               , "SLL L"             },
	{ &CZ80Core::SLL_off_HL          , "SLL (HL)"          },
	{ &CZ80Core::SLL_A               , "SLL A"             },
	{ &CZ80Core::SRL_B               , "SRL B"             },
	{ &CZ80Core::SRL_C               , "SRL C"             },
	{ &CZ80Core::SRL_D               , "SRL D"             },
	{ &CZ80Core::SRL_E               , "SRL E"             },
	{ &CZ80Core::SRL_H               , "SRL H"             },
	{ &CZ80Core::SRL_L               , "SRL L"             },
	{ &CZ80Core::SRL_off_HL          , "SRL (HL)"          },
	{ &CZ80Core::SRL_A               , "SRL A"             },
	{ &CZ80Core::BIT_0_B             , "BIT 0,B"           },
	{ &CZ80Core::BIT_0_C             , "BIT 0,C"           },
	{ &CZ80Core::BIT_0_D             , "BIT 0,D"           },
	{ &CZ80Core::BIT_0_E             , "BIT 0,E"           },
	{ &CZ80Core::BIT_0_H             , "BIT 0,H"           },
	{ &CZ80Core::BIT_0_L             , "BIT 0,L"           },
	{ &CZ80Core::BIT_0_off_HL        , "BIT 0,(HL)"        },
	{ &CZ80Core::BIT_0_A             , "BIT 0,A"           },
	{ &CZ80Core::BIT_1_B             , "BIT 1,B"           },
	{ &CZ80Core::BIT_1_C             , "BIT 1,C"           },
	{ &CZ80Core::BIT_1_D             , "BIT 1,D"           },
	{ &CZ80Core::BIT_1_E             , "BIT 1,E"           },
	{ &CZ80Core::BIT_1_H             , "BIT 1,H"           },
	{ &CZ80Core::BIT_1_L             , "BIT 1,L"           },
	{ &CZ80Core::BIT_1_off_HL        , "BIT 1,(HL)"        },
	{ &CZ80Core::BIT_1_A             , "BIT 1,A"           },
	{ &CZ80Core::BIT_2_B             , "BIT 2,B"           },
	{ &CZ80Core::BIT_2_C             , "BIT 2,C"           },
	{ &CZ80Core::BIT_2_D             , "BIT 2,D"           },
	{ &CZ80Core::BIT_2_E             , "BIT 2,E"           },
	{ &CZ80Core::BIT_2_H             , "BIT 2,H"           },
	{ &CZ80Core::BIT_2_L             , "BIT 2,L"           },
	{ &CZ80Core::BIT_2_off_HL        , "BIT 2,(HL)"        },
	{ &CZ80Core::BIT_2_A             , "BIT 2,A"           },
	{ &CZ80Core::BIT_3_B             , "BIT 3,B"           },
	{ &CZ80Core::BIT_3_C             , "BIT 3,C"           },
	{ &CZ80Core::BIT_3_D             , "BIT 3,D"           },
	{ &CZ80Core::BIT_3_E             , "BIT 3,E"           },
	{ &CZ80Core::BIT_3_H             , "BIT 3,H"           },
	{ &CZ80Core::BIT_3_L             , "BIT 3,L"           },
	{ &CZ80Core::BIT_3_off_HL        , "BIT 3,(HL)"        },
	{ &CZ80Core::BIT_3_A             , "BIT 3,A"           },
	{ &CZ80Core::BIT_4_B             , "BIT 4,B"           },
	{ &CZ80Core::BIT_4_C             , "BIT 4,C"           },
	{ &CZ80Core::BIT_4_D             , "BIT 4,D"           },
	{ &CZ80Core::BIT_4_E             , "BIT 4,E"           },
	{ &CZ80Core::BIT_4_H             , "BIT 4,H"           },
	{ &CZ80Core::BIT_4_L             , "BIT 4,L"           },
	{ &CZ80Core::BIT_4_off_HL        , "BIT 4,(HL)"        },
	{ &CZ80Core::BIT_4_A             , "BIT 4,A"           },
	{ &CZ80Core::BIT_5_B             , "BIT 5,B"           },
	{ &CZ80Core::BIT_5_C             , "BIT 5,C"           },
	{ &CZ80Core::BIT_5_D             , "BIT 5,D"           },
	{ &CZ80Core::BIT_5_E             , "BIT 5,E"           },
	{ &CZ80Core::BIT_5_H             , "BIT 5,H"           },
	{ &CZ80Core::BIT_5_L             , "BIT 5,L"           },
	{ &CZ80Core::BIT_5_off_HL        , "BIT 5,(HL)"        },
	{ &CZ80Core::BIT_5_A             , "BIT 5,A"           },
	{ &CZ80Core::BIT_6_B             , "BIT 6,B"           },
	{ &CZ80Core::BIT_6_C             , "BIT 6,C"           },
	{ &CZ80Core::BIT_6_D             , "BIT 6,D"           },
	{ &CZ80Core::BIT_6_E             , "BIT 6,E"           },
	{ &CZ80Core::BIT_6_H             , "BIT 6,H"           },
	{ &CZ80Core::BIT_6_L             , "BIT 6,L"           },
	{ &CZ80Core::BIT_6_off_HL        , "BIT 6,(HL)"        },
	{ &CZ80Core::BIT_6_A             , "BIT 6,A"           },
	{ &CZ80Core::BIT_7_B             , "BIT 7,B"           },
	{ &CZ80Core::BIT_7_C             , "BIT 7,C"           },
	{ &CZ80Core::BIT_7_D             , "BIT 7,D"           },
	{ &CZ80Core::BIT_7_E             , "BIT 7,E"           },
	{ &CZ80Core::BIT_7_H             , "BIT 7,H"           },
	{ &CZ80Core::BIT_7_L             , "BIT 7,L"           },
	{ &CZ80Core::BIT_7_off_HL        , "BIT 7,(HL)"        },
	{ &CZ80Core::BIT_7_A             , "BIT 7,A"           },
	{ &CZ80Core::RES_0_B             , "RES 0,B"           },
	{ &CZ80Core::RES_0_C             , "RES 0,C"           },
	{ &CZ80Core::RES_0_D             , "RES 0,D"           },
	{ &CZ80Core::RES_0_E             , "RES 0,E"           },
	{ &CZ80Core::RES_0_H             , "RES 0,H"           },
	{ &CZ80Core::RES_0_L             , "RES 0,L"           },
	{ &CZ80Core::RES_0_off_HL        , "RES 0,(HL)"        },
	{ &CZ80Core::RES_0_A             , "RES 0,A"           },
	{ &CZ80Core::RES_1_B             , "RES 1,B"           },
	{ &CZ80Core::RES_1_C             , "RES 1,C"           },
	{ &CZ80Core::RES_1_D             , "RES 1,D"           },
	{ &CZ80Core::RES_1_E             , "RES 1,E"           },
	{ &CZ80Core::RES_1_H             , "RES 1,H"           },
	{ &CZ80Core::RES_1_L             , "RES 1,L"           },
	{ &CZ80Core::RES_1_off_HL        , "RES 1,(HL)"        },
	{ &CZ80Core::RES_1_A             , "RES 1,A"           },
	{ &CZ80Core::RES_2_B             , "RES 2,B"           },
	{ &CZ80Core::RES_2_C             , "RES 2,C"           },
	{ &CZ80Core::RES_2_D             , "RES 2,D"           },
	{ &CZ80Core::RES_2_E             , "RES 2,E"           },
	{ &CZ80Core::RES_2_H             , "RES 2,H"           },
	{ &CZ80Core::RES_2_L             , "RES 2,L"           },
	{ &CZ80Core::RES_2_off_HL        , "RES 2,(HL)"        },
	{ &CZ80Core::RES_2_A             , "RES 2,A"           },
	{ &CZ80Core::RES_3_B             , "RES 3,B"           },
	{ &CZ80Core::RES_3_C             , "RES 3,C"           },
	{ &CZ80Core::RES_3_D             , "RES 3,D"           },
	{ &CZ80Core::RES_3_E             , "RES 3,E"           },
	{ &CZ80Core::RES_3_H             , "RES 3,H"           },
	{ &CZ80Core::RES_3_L             , "RES 3,L"           },
	{ &CZ80Core::RES_3_off_HL        , "RES 3,(HL)"        },
	{ &CZ80Core::RES_3_A             , "RES 3,A"           },
	{ &CZ80Core::RES_4_B             , "RES 4,B"           },
	{ &CZ80Core::RES_4_C             , "RES 4,C"           },
	{ &CZ80Core::RES_4_D             , "RES 4,D"           },
	{ &CZ80Core::RES_4_E             , "RES 4,E"           },
	{ &CZ80Core::RES_4_H             , "RES 4,H"           },
	{ &CZ80Core::RES_4_L             , "RES 4,L"           },
	{ &CZ80Core::RES_4_off_HL        , "RES 4,(HL)"        },
	{ &CZ80Core::RES_4_A             , "RES 4,A"           },
	{ &CZ80Core::RES_5_B             , "RES 5,B"           },
	{ &CZ80Core::RES_5_C             , "RES 5,C"           },
	{ &CZ80Core::RES_5_D             , "RES 5,D"           },
	{ &CZ80Core::RES_5_E             , "RES 5,E"           },
	{ &CZ80Core::RES_5_H             , "RES 5,H"           },
	{ &CZ80Core::RES_5_L             , "RES 5,L"           },
	{ &CZ80Core::RES_5_off_HL        , "RES 5,(HL)"        },
	{ &CZ80Core::RES_5_A             , "RES 5,A"           },
	{ &CZ80Core::RES_6_B             , "RES 6,B"           },
	{ &CZ80Core::RES_6_C             , "RES 6,C"           },
	{ &CZ80Core::RES_6_D             , "RES 6,D"           },
	{ &CZ80Core::RES_6_E             , "RES 6,E"           },
	{ &CZ80Core::RES_6_H             , "RES 6,H"           },
	{ &CZ80Core::RES_6_L             , "RES 6,L"           },
	{ &CZ80Core::RES_6_off_HL        , "RES 6,(HL)"        },
	{ &CZ80Core::RES_6_A             , "RES 6,A"           },
	{ &CZ80Core::RES_7_B             , "RES 7,B"           },
	{ &CZ80Core::RES_7_C             , "RES 7,C"           },
	{ &CZ80Core::RES_7_D             , "RES 7,D"           },
	{ &CZ80Core::RES_7_E             , "RES 7,E"           },
	{ &CZ80Core::RES_7_H             , "RES 7,H"           },
	{ &CZ80Core::RES_7_L             , "RES 7,L"           },
	{ &CZ80Core::RES_7_off_HL        , "RES 7,(HL)"        },
	{ &CZ80Core::RES_7_A             , "RES 7,A"           },
	{ &CZ80Core::SET_0_B             , "SET 0,B"           },
	{ &CZ80Core::SET_0_C             , "SET 0,C"           },
	{ &CZ80Core::SET_0_D             , "SET 0,D"           },
	{ &CZ80Core::SET_0_E             , "SET 0,E"           },
	{ &CZ80Core::SET_0_H             , "SET 0,H"           },
	{ &CZ80Core::SET_0_L             , "SET 0,L"           },
	{ &CZ80Core::SET_0_off_HL        , "SET 0,(HL)"        },
	{ &CZ80Core::SET_0_A             , "SET 0,A"           },
	{ &CZ80Core::SET_1_B             , "SET 1,B"           },
	{ &CZ80Core::SET_1_C             , "SET 1,C"           },
	{ &CZ80Core::SET_1_D             , "SET 1,D"           },
	{ &CZ80Core::SET_1_E             , "SET 1,E"           },
	{ &CZ80Core::SET_1_H             , "SET 1,H"           },
	{ &CZ80Core::SET_1_L             , "SET 1,L"           },
	{ &CZ80Core::SET_1_off_HL        , "SET 1,(HL)"        },
	{ &CZ80Core::SET_1_A             , "SET 1,A"           },
	{ &CZ80Core::SET_2_B             , "SET 2,B"           },
	{ &CZ80Core::SET_2_C             , "SET 2,C"           },
	{ &CZ80Core::SET_2_D             , "SET 2,D"           },
	{ &CZ80Core::SET_2_E             , "SET 2,E"           },
	{ &CZ80Core::SET_2_H             , "SET 2,H"           },
	{ &CZ80Core::SET_2_L             , "SET 2,L"           },
	{ &CZ80Core::SET_2_off_HL        , "SET 2,(HL)"        },
	{ &CZ80Core::SET_2_A             , "SET 2,A"           },
	{ &CZ80Core::SET_3_B             , "SET 3,B"           },
	{ &CZ80Core::SET_3_C             , "SET 3,C"           },
	{ &CZ80Core::SET_3_D             , "SET 3,D"           },
	{ &CZ80Core::SET_3_E             , "SET 3,E"           },
	{ &CZ80Core::SET_3_H             , "SET 3,H"           },
	{ &CZ80Core::SET_3_L             , "SET 3,L"           },
	{ &CZ80Core::SET_3_off_HL        , "SET 3,(HL)"        },
	{ &CZ80Core::SET_3_A             , "SET 3,A"           },
	{ &CZ80Core::SET_4_B             , "SET 4,B"           },
	{ &CZ80Core::SET_4_C             , "SET 4,C"           },
	{ &CZ80Core::SET_4_D             , "SET 4,D"           },
	{ &CZ80Core::SET_4_E             , "SET 4,E"           },
	{ &CZ80Core::SET_4_H             , "SET 4,H"           },
	{ &CZ80Core::SET_4_L             , "SET 4,L"           },
	{ &CZ80Core::SET_4_off_HL        , "SET 4,(HL)"        },
	{ &CZ80Core::SET_4_A             , "SET 4,A"           },
	{ &CZ80Core::SET_5_B             , "SET 5,B"           },
	{ &CZ80Core::SET_5_C             , "SET 5,C"           },
	{ &CZ80Core::SET_5_D             , "SET 5,D"           },
	{ &CZ80Core::SET_5_E             , "SET 5,E"           },
	{ &CZ80Core::SET_5_H             , "SET 5,H"           },
	{ &CZ80Core::SET_5_L             , "SET 5,L"           },
	{ &CZ80Core::SET_5_off_HL        , "SET 5,(HL)"        },
	{ &CZ80Core::SET_5_A             , "SET 5,A"           },
	{ &CZ80Core::SET_6_B             , "SET 6,B"           },
	{ &CZ80Core::SET_6_C             , "SET 6,C"           },
	{ &CZ80Core::SET_6_D             , "SET 6,D"           },
	{ &CZ80Core::SET_6_E             , "SET 6,E"           },
	{ &CZ80Core::SET_6_H             , "SET 6,H"           },
	{ &CZ80Core::SET_6_L             , "SET 6,L"           },
	{ &CZ80Core::SET_6_off_HL        , "SET 6,(HL)"        },
	{ &CZ80Core::SET_6_A             , "SET 6,A"           },
	{ &CZ80Core::SET_7_B             , "SET 7,B"           },
	{ &CZ80Core::SET_7_C             , "SET 7,C"           },
	{ &CZ80Core::SET_7_D             , "SET 7,D"           },
	{ &CZ80Core::SET_7_E             , "SET 7,E"           },
	{ &CZ80Core::SET_7_H             , "SET 7,H"           },
	{ &CZ80Core::SET_7_L             , "SET 7,L"           },
	{ &CZ80Core::SET_7_off_HL        , "SET 7,(HL)"        },
	{ &CZ80Core::SET_7_A             , "SET 7,A"           }
} };


CZ80Core::Z80OpcodeTable CZ80Core::DD_Opcodes = {
{
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::ADD_IX_BC           , "ADD IX,BC"         },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::ADD_IX_DE           , "ADD IX,DE"         },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_IX_nn            , "LD IX,0%04Xh"      },
	{ &CZ80Core::LD_off_nn_IX        , "LD (0%04Xh),IX"    },
	{ &CZ80Core::INC_IX              , "INC IX"            },
	{ &CZ80Core::INC_IXh             , "INC IXh"           },
	{ &CZ80Core::DEC_IXh             , "DEC IXh"           },
	{ &CZ80Core::LD_IXh_n            , "LD IXh,0%02Xh"     },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::ADD_IX_IX           , "ADD IX,IX"         },
	{ &CZ80Core::LD_IX_off_nn        , "LD IX,(0%04Xh)"    },
	{ &CZ80Core::DEC_IX              , "DEC IX"            },
	{ &CZ80Core::INC_IXl             , "INC IXl"           },
	{ &CZ80Core::DEC_IXl             , "DEC IXl"           },
	{ &CZ80Core::LD_IXl_n            , "LD IXl,0%02Xh"     },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::INC_off_IX_d        , "INC (IX+0%02Xh)"   },
	{ &CZ80Core::DEC_off_IX_d        , "DEC (IX+0%02Xh)"   },
	{ &CZ80Core::LD_off_IX_d_n       , "LD (IX+0%02Xh),0%02Xh"},
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::ADD_IX_SP           , "ADD IX,SP"         },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_B_IXh            , "LD B,IXh"          },
	{ &CZ80Core::LD_B_IXl            , "LD B,IXl"          },
	{ &CZ80Core::LD_B_off_IX_d       , "LD B,(IX+0%02Xh)"  },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_C_IXh            , "LD C,IXh"          },
	{ &CZ80Core::LD_C_IXl            , "LD C,IXl"          },
	{ &CZ80Core::LD_C_off_IX_d       , "LD C,(IX+0%02Xh)"  },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_D_IXh            , "LD D,IXh"          },
	{ &CZ80Core::LD_D_IXl            , "LD D,IXl"          },
	{ &CZ80Core::LD_D_off_IX_d       , "LD D,(IX+0%02Xh)"  },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_E_IXh            , "LD E,IXh"          },
	{ &CZ80Core::LD_E_IXl            , "LD E,IXl"          },
	{ &CZ80Core::LD_E_off_IX_d       , "LD E,(IX+0%02Xh)"  },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_IXh_B            , "LD IXh,B"          },
	{ &CZ80Core::LD_IXh_C            , "LD IXh,C"          },
	{ &CZ80Core::LD_IXh_D            , "LD IXh,D"          },
	{ &CZ80Core::LD_IXh_E            , "LD IXh,E"          },
	{ &CZ80Core::LD_IXh_IXh          , "LD IXh,IXh"        },
	{ &CZ80Core::LD_IXh_IXl          , "LD IXh,IXl"        },
	{ &CZ80Core::LD_H_off_IX_d       , "LD H,(IX+0%02Xh)"  },
	{ &CZ80Core::LD_IXh_A            , "LD IXh,A"          },
	{ &CZ80Core::LD_IXl_B            , "LD IXl,B"          },
	{ &CZ80Core::LD_IXl_C            , "LD IXl,C"          },
	{ &CZ80Core::LD_IXl_D            , "LD IXl,D"          },
	{ &CZ80Core::LD_IXl_E            , "LD IXl,E"          },
	{ &CZ80Core::LD_IXl_IXh          , "LD IXl,IXh"        },
	{ &CZ80Core::LD_IXl_IXl          , "LD IXl,IXl"        },
	{ &CZ80Core::LD_L_off_IX_d       , "LD L,(IX+0%02Xh)"  },
	{ &CZ80Core::LD_IXl_A            , "LD IXl,A"          },
	{ &CZ80Core::LD_off_IX_d_B       , "LD (IX+0%02Xh),B"  },
	{ &CZ80Core::LD_off_IX_d_C       , "LD (IX+0%02Xh),C"  },
	{ &CZ80Core::LD_off_IX_d_D       , "LD (IX+0%02Xh),D"  },
	{ &CZ80Core::LD_off_IX_d_E       , "LD (IX+0%02Xh),E"  },
	{ &CZ80Core::LD_off_IX_d_H       , "LD (IX+0%02Xh),H"  },
	{ &CZ80Core::LD_off_IX_d_L       , "LD (IX+0%02Xh),L"  },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_off_IX_d_A       , "LD (IX+0%02Xh),A"  },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_A_IXh            , "LD A,IXh"          },
	{ &CZ80Core::LD_A_IXl            , "LD A,IXl"          },
	{ &CZ80Core::LD_A_off_IX_d       , "LD A,(IX+0%02Xh)"  },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::ADD_A_IXh           , "ADD A,IXh"         },
	{ &CZ80Core::ADD_A_IXl           , "ADD A,IXl"         },
	{ &CZ80Core::ADD_A_off_IX_d      , "ADD A,(IX+0%02Xh)" },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::ADC_A_IXh           , "ADC A,IXh"         },
	{ &CZ80Core::ADC_A_IXl           , "ADC A,IXl"         },
	{ &CZ80Core::ADC_A_off_IX_d      , "ADC A,(IX+0%02Xh)" },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::SUB_A_IXh           , "SUB A,IXh"         },
	{ &CZ80Core::SUB_A_IXl           , "SUB A,IXl"         },
	{ &CZ80Core::SUB_A_off_IX_d      , "SUB A,(IX+0%02Xh)" },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::SBC_A_IXh           , "SBC A,IXh"         },
	{ &CZ80Core::SBC_A_IXl           , "SBC A,IXl"         },
	{ &CZ80Core::SBC_A_off_IX_d      , "SBC A,(IX+0%02Xh)" },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::AND_IXh             , "AND IXh"           },
	{ &CZ80Core::AND_IXl             , "AND IXl"           },
	{ &CZ80Core::AND_off_IX_d        , "AND (IX+0%02Xh)"   },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::XOR_IXh             , "XOR IXh"           },
	{ &CZ80Core::XOR_IXl             , "XOR IXl"           },
	{ &CZ80Core::XOR_off_IX_d        , "XOR (IX+0%02Xh)"   },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::OR_IXh              , "OR IXh"            },
	{ &CZ80Core::OR_IXl              , "OR IXl"            },
	{ &CZ80Core::OR_off_IX_d         , "OR (IX+0%02Xh)"    },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::CP_IXh              , "CP IXh"            },
	{ &CZ80Core::CP_IXl              , "CP IXl"            },
	{ &CZ80Core::CP_off_IX_d         , "CP (IX+0%02Xh)"    },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::POP_IX              , "POP IX"            },
	{ NULL							, NULL				   },
	{ &CZ80Core::EX_off_SP_IX        , "EX (SP),IX"        },
	{ NULL							, NULL				   },
	{ &CZ80Core::PUSH_IX             , "PUSH IX"           },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::JP_off_IX           , "JP (IX)"           },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LD_SP_IX            , "LD SP,IX"          },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                }
} };


CZ80Core::Z80OpcodeTable CZ80Core::ED_Opcodes = {
{
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::IN_B_off_C          , "IN B,(C)"          },
	{ &CZ80Core::OUT_off_C_B         , "OUT (C),B"         },
	{ &CZ80Core::SBC_HL_BC           , "SBC HL,BC"         },
	{ &CZ80Core::LD_off_nn_BC        , "LD (0%04Xh),BC"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETN                , "RETN"              },
	{ &CZ80Core::IM_0                , "IM 0"              },
	{ &CZ80Core::LD_I_A              , "LD I,A"            },
	{ &CZ80Core::IN_C_off_C          , "IN C,(C)"          },
	{ &CZ80Core::OUT_off_C_C         , "OUT (C),C"         },
	{ &CZ80Core::ADC_HL_BC           , "ADC HL,BC"         },
	{ &CZ80Core::LD_BC_off_nn        , "LD BC,(0%04Xh)"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETI                , "RETI"              },
	{ &CZ80Core::IM_0                , "IM 0"              },
	{ &CZ80Core::LD_R_A              , "LD R,A"            },
	{ &CZ80Core::IN_D_off_C          , "IN D,(C)"          },
	{ &CZ80Core::OUT_off_C_D         , "OUT (C),D"         },
	{ &CZ80Core::SBC_HL_DE           , "SBC HL,DE"         },
	{ &CZ80Core::LD_off_nn_DE        , "LD (0%04Xh),DE"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETN                , "RETN"              },
	{ &CZ80Core::IM_1                , "IM 1"              },
	{ &CZ80Core::LD_A_I              , "LD A,I"            },
	{ &CZ80Core::IN_E_off_C          , "IN E,(C)"          },
	{ &CZ80Core::OUT_off_C_E         , "OUT (C),E"         },
	{ &CZ80Core::ADC_HL_DE           , "ADC HL,DE"         },
	{ &CZ80Core::LD_DE_off_nn        , "LD DE,(0%04Xh)"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETN                , "RETN"              },
	{ &CZ80Core::IM_2                , "IM 2"              },
	{ &CZ80Core::LD_A_R              , "LD A,R"            },
	{ &CZ80Core::IN_H_off_C          , "IN H,(C)"          },
	{ &CZ80Core::OUT_off_C_H         , "OUT (C),H"         },
	{ &CZ80Core::SBC_HL_HL           , "SBC HL,HL"         },
	{ &CZ80Core::LD_off_nn_HL        , "LD (0%04Xh),HL"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETN                , "RETN"              },
	{ &CZ80Core::IM_0                , "IM 0"              },
	{ &CZ80Core::RRD                 , "RRD"               },
	{ &CZ80Core::IN_L_off_C          , "IN L,(C)"          },
	{ &CZ80Core::OUT_off_C_L         , "OUT (C),L"         },
	{ &CZ80Core::ADC_HL_HL           , "ADC HL,HL"         },
	{ &CZ80Core::LD_HL_off_nn        , "LD HL,(0%04Xh)"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETN                , "RETN"              },
	{ &CZ80Core::IM_0                , "IM 0"              },
	{ &CZ80Core::RLD                 , "RLD"               },
	{ &CZ80Core::IN_F_off_C          , "IN F,(C)"          },
	{ &CZ80Core::OUT_off_C_0         , "OUT (C),0"         },
	{ &CZ80Core::SBC_HL_SP           , "SBC HL,SP"         },
	{ &CZ80Core::LD_off_nn_SP        , "LD (0%04Xh),SP"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETN                , "RETN"              },
	{ &CZ80Core::IM_1                , "IM 1"              },
	{ NULL							 , NULL                },
	{ &CZ80Core::IN_A_off_C          , "IN A,(C)"          },
	{ &CZ80Core::OUT_off_C_A         , "OUT (C),A"         },
	{ &CZ80Core::ADC_HL_SP           , "ADC HL,SP"         },
	{ &CZ80Core::LD_SP_off_nn        , "LD SP,(0%04Xh)"    },
	{ &CZ80Core::NEG                 , "NEG"               },
	{ &CZ80Core::RETN                , "RETN"              },
	{ &CZ80Core::IM_2                , "IM 2"              },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LDI                 , "LDI"               },
	{ &CZ80Core::CPI                 , "CPI"               },
	{ &CZ80Core::INI                 , "INI"               },
	{ &CZ80Core::OUTI                , "OUTI"              },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LDD                 , "LDD"               },
	{ &CZ80Core::CPD                 , "CPD"               },
	{ &CZ80Core::IND                 , "IND"               },
	{ &CZ80Core::OUTD                , "OUTD"              },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LDIR                , "LDIR"              },
	{ &CZ80Core::CPIR                , "CPIR"              },
	{ &CZ80Core::INIR                , "INIR"              },
	{ &CZ80Core::OTIR                , "OTIR"              },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ &CZ80Core::LDDR                , "LDDR"              },
	{ &CZ80Core::CPDR                , "CPDR"              },
	{ &CZ80Core::INDR                , "INDR"              },
	{ &CZ80Core::OTDR                , "OTDR"              },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                },
	{ NULL							 , NULL                }
} };


CZ80Core::Z80OpcodeTable CZ80Core::FD_Opcodes = {
{
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ &CZ80Core::ADD_IY_BC           , "ADD IY,BC"			},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ &CZ80Core::ADD_IY_DE           , "ADD IY,DE"			},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ &CZ80Core::LD_IY_nn            , "LD IY,0%04Xh"		},
	{ &CZ80Core::LD_off_nn_IY        , "LD (0%04Xh),IY"		},
	{ &CZ80Core::INC_IY              , "INC IY"				},
	{ &CZ80Core::INC_IYh             , "INC IYh"			},
	{ &CZ80Core::DEC_IYh             , "DEC IYh"			},
	{ &CZ80Core::LD_IYh_n            , "LD IYh,0%02Xh"		},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ &CZ80Core::ADD_IY_IY           , "ADD IY,IY"			},
	{ &CZ80Core::LD_IY_off_nn        , "LD IY,(0%04Xh)"		},
	{ &CZ80Core::DEC_IY              , "DEC IY"				},
	{ &CZ80Core::INC_IYl             , "INC IYl"			},
	{ &CZ80Core::DEC_IYl             , "DEC IYl"			},
	{ &CZ80Core::LD_IYl_n            , "LD IYl,0%02Xh"		},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ NULL							, NULL					},
	{ &CZ80Core::INC_off_IY_d        , "INC (IY+0%02Xh)"	},
	{ &CZ80Core::DEC_off_IY_d        , "DEC (IY+0%02Xh)"	},
	{ &CZ80Core::LD_off_IY_d_n       , "LD (IY+0%02Xh),0%02Xh"},
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::ADD_IY_SP          , "ADD IY,SP"         },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_B_IYh            , "LD B,IYh"         },
	{ &CZ80Core::LD_B_IYl            , "LD B,IYl"         },
	{ &CZ80Core::LD_B_off_IY_d       , "LD B,(IY+0%02Xh)" },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_C_IYh            , "LD C,IYh"         },
	{ &CZ80Core::LD_C_IYl            , "LD C,IYl"         },
	{ &CZ80Core::LD_C_off_IY_d       , "LD C,(IY+0%02Xh)" },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_D_IYh            , "LD D,IYh"         },
	{ &CZ80Core::LD_D_IYl            , "LD D,IYl"         },
	{ &CZ80Core::LD_D_off_IY_d       , "LD D,(IY+0%02Xh)" },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_E_IYh            , "LD E,IYh"         },
	{ &CZ80Core::LD_E_IYl            , "LD E,IYl"         },
	{ &CZ80Core::LD_E_off_IY_d       , "LD E,(IY+0%02Xh)" },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_IYh_B            , "LD IYh,B"         },
	{ &CZ80Core::LD_IYh_C            , "LD IYh,C"         },
	{ &CZ80Core::LD_IYh_D            , "LD IYh,D"         },
	{ &CZ80Core::LD_IYh_E            , "LD IYh,E"         },
	{ &CZ80Core::LD_IYh_IYh          , "LD IYh,IYh"       },
	{ &CZ80Core::LD_IYh_IYl          , "LD IYh,IYl"       },
	{ &CZ80Core::LD_H_off_IY_d       , "LD H,(IY+0%02Xh)" },
	{ &CZ80Core::LD_IYh_A            , "LD IYh,A"         },
	{ &CZ80Core::LD_IYl_B            , "LD IYl,B"         },
	{ &CZ80Core::LD_IYl_C            , "LD IYl,C"         },
	{ &CZ80Core::LD_IYl_D            , "LD IYl,D"         },
	{ &CZ80Core::LD_IYl_E            , "LD IYl,E"         },
	{ &CZ80Core::LD_IYl_IYh          , "LD IYl,IYh"       },
	{ &CZ80Core::LD_IYl_IYl          , "LD IYl,IYl"       },
	{ &CZ80Core::LD_L_off_IY_d       , "LD L,(IY+0%02Xh)" },
	{ &CZ80Core::LD_IYl_A            , "LD IYl,A"         },
	{ &CZ80Core::LD_off_IY_d_B       , "LD (IY+0%02Xh),B" },
	{ &CZ80Core::LD_off_IY_d_C       , "LD (IY+0%02Xh),C" },
	{ &CZ80Core::LD_off_IY_d_D       , "LD (IY+0%02Xh),D" },
	{ &CZ80Core::LD_off_IY_d_E       , "LD (IY+0%02Xh),E" },
	{ &CZ80Core::LD_off_IY_d_H       , "LD (IY+0%02Xh),H" },
	{ &CZ80Core::LD_off_IY_d_L       , "LD (IY+0%02Xh),L" },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_off_IY_d_A       , "LD (IY+0%02Xh),A" },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_A_IYh            , "LD A,IYh"         },
	{ &CZ80Core::LD_A_IYl            , "LD A,IYl"         },
	{ &CZ80Core::LD_A_off_IY_d       , "LD A,(IY+0%02Xh)" },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::ADD_A_IYh           , "ADD A,IYh"        },
	{ &CZ80Core::ADD_A_IYl           , "ADD A,IYl"        },
	{ &CZ80Core::ADD_A_off_IY_d      , "ADD A,(IY+0%02Xh)"},
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::ADC_A_IYh           , "ADC A,IYh"        },
	{ &CZ80Core::ADC_A_IYl           , "ADC A,IYl"        },
	{ &CZ80Core::ADC_A_off_IY_d      , "ADC A,(IY+0%02Xh)"},
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::SUB_A_IYh           , "SUB A,IYh"        },
	{ &CZ80Core::SUB_A_IYl           , "SUB A,IYl"        },
	{ &CZ80Core::SUB_A_off_IY_d      , "SUB A,(IY+0%02Xh)"},
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::SBC_A_IYh           , "SBC A,IYh"        },
	{ &CZ80Core::SBC_A_IYl           , "SBC A,IYl"        },
	{ &CZ80Core::SBC_A_off_IY_d      , "SBC A,(IY+0%02Xh)"},
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::AND_IYh             , "AND IYh"          },
	{ &CZ80Core::AND_IYl             , "AND IYl"          },
	{ &CZ80Core::AND_off_IY_d        , "AND (IY+0%02Xh)"  },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::XOR_IYh             , "XOR IYh"           },
	{ &CZ80Core::XOR_IYl             , "XOR IYl"           },
	{ &CZ80Core::XOR_off_IY_d        , "XOR (IY+0%02Xh)"   },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::OR_IYh              , "OR IYh"            },
	{ &CZ80Core::OR_IYl              , "OR IYl"            },
	{ &CZ80Core::OR_off_IY_d         , "OR (IY+0%02Xh)"    },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::CP_IYh              , "CP IYh"            },
	{ &CZ80Core::CP_IYl              , "CP IYl"            },
	{ &CZ80Core::CP_off_IY_d         , "CP (IY+0%02Xh)"    },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::POP_IY              , "POP IY"            },
	{ NULL							, NULL                },
	{ &CZ80Core::EX_off_SP_IY        , "EX (SP),IY"        },
	{ NULL							, NULL                },
	{ &CZ80Core::PUSH_IY             , "PUSH IY"           },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::JP_off_IY           , "JP (IY)"           },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ &CZ80Core::LD_SP_IY            , "LD SP,IY"          },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                },
	{ NULL							, NULL                }
} };


CZ80Core::Z80OpcodeTable CZ80Core::DDCB_Opcodes = {
{
	{ &CZ80Core::LD_B_RLC_off_IX_IY_d   , "LD B,RLC (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RLC_off_IX_IY_d   , "LD C,RLC (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RLC_off_IX_IY_d   , "LD D,RLC (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RLC_off_IX_IY_d   , "LD E,RLC (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RLC_off_IX_IY_d   , "LD H,RLC (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RLC_off_IX_IY_d   , "LD L,RLC (IX+0%02Xh)" },
	{ &CZ80Core::RLC_off_IX_IY_d        , "RLC (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RLC_off_IX_IY_d   , "LD A,RLC (IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RRC_off_IX_IY_d   , "LD B,RRC (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RRC_off_IX_IY_d   , "LD C,RRC (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RRC_off_IX_IY_d   , "LD D,RRC (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RRC_off_IX_IY_d   , "LD E,RRC (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RRC_off_IX_IY_d   , "LD H,RRC (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RRC_off_IX_IY_d   , "LD L,RRC (IX+0%02Xh)" },
	{ &CZ80Core::RRC_off_IX_IY_d        , "RRC (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RRC_off_IX_IY_d   , "LD A,RRC (IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RL_off_IX_IY_d    , "LD B,RL (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RL_off_IX_IY_d    , "LD C,RL (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RL_off_IX_IY_d    , "LD D,RL (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RL_off_IX_IY_d    , "LD E,RL (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RL_off_IX_IY_d    , "LD H,RL (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RL_off_IX_IY_d    , "LD L,RL (IX+0%02Xh)" },
	{ &CZ80Core::RL_off_IX_IY_d         , "RL (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RL_off_IX_IY_d    , "LD A,RL (IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RR_off_IX_IY_d    , "LD B,RR (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RR_off_IX_IY_d    , "LD C,RR (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RR_off_IX_IY_d    , "LD D,RR (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RR_off_IX_IY_d    , "LD E,RR (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RR_off_IX_IY_d    , "LD H,RR (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RR_off_IX_IY_d    , "LD L,RR (IX+0%02Xh)" },
	{ &CZ80Core::RR_off_IX_IY_d         , "RR (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RR_off_IX_IY_d    , "LD A,RR (IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SLA_off_IX_IY_d   , "LD B,SLA (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SLA_off_IX_IY_d   , "LD C,SLA (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SLA_off_IX_IY_d   , "LD D,SLA (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SLA_off_IX_IY_d   , "LD E,SLA (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SLA_off_IX_IY_d   , "LD H,SLA (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SLA_off_IX_IY_d   , "LD L,SLA (IX+0%02Xh)" },
	{ &CZ80Core::SLA_off_IX_IY_d        , "SLA (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SLA_off_IX_IY_d   , "LD A,SLA (IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SRA_off_IX_IY_d   , "LD B,SRA (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SRA_off_IX_IY_d   , "LD C,SRA (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SRA_off_IX_IY_d   , "LD D,SRA (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SRA_off_IX_IY_d   , "LD E,SRA (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SRA_off_IX_IY_d   , "LD H,SRA (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SRA_off_IX_IY_d   , "LD L,SRA (IX+0%02Xh)" },
	{ &CZ80Core::SRA_off_IX_IY_d        , "SRA (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SRA_off_IX_IY_d   , "LD A,SRA (IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SLL_off_IX_IY_d   , "LD B,SLL (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SLL_off_IX_IY_d   , "LD C,SLL (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SLL_off_IX_IY_d   , "LD D,SLL (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SLL_off_IX_IY_d   , "LD E,SLL (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SLL_off_IX_IY_d   , "LD H,SLL (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SLL_off_IX_IY_d   , "LD L,SLL (IX+0%02Xh)" },
	{ &CZ80Core::SLL_off_IX_IY_d        , "SLL (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SLL_off_IX_IY_d   , "LD A,SLL (IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SRL_off_IX_IY_d   , "LD B,SRL (IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SRL_off_IX_IY_d   , "LD C,SRL (IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SRL_off_IX_IY_d   , "LD D,SRL (IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SRL_off_IX_IY_d   , "LD E,SRL (IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SRL_off_IX_IY_d   , "LD H,SRL (IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SRL_off_IX_IY_d   , "LD L,SRL (IX+0%02Xh)" },
	{ &CZ80Core::SRL_off_IX_IY_d        , "SRL (IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SRL_off_IX_IY_d   , "LD A,SRL (IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_0_off_IX_IY_d      , "BIT 0,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_1_off_IX_IY_d      , "BIT 1,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_2_off_IX_IY_d      , "BIT 2,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_3_off_IX_IY_d      , "BIT 3,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_4_off_IX_IY_d      , "BIT 4,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_5_off_IX_IY_d      , "BIT 5,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_6_off_IX_IY_d      , "BIT 6,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::BIT_7_off_IX_IY_d      , "BIT 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_0_off_IX_IY_d , "LD B,RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_0_off_IX_IY_d , "LD C,RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_0_off_IX_IY_d , "LD D,RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_0_off_IX_IY_d , "LD E,RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_0_off_IX_IY_d , "LD H,RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_0_off_IX_IY_d , "LD L,RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::RES_0_off_IX_IY_d      , "RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_0_off_IX_IY_d , "LD A,RES 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_1_off_IX_IY_d , "LD B,RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_1_off_IX_IY_d , "LD C,RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_1_off_IX_IY_d , "LD D,RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_1_off_IX_IY_d , "LD E,RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_1_off_IX_IY_d , "LD H,RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_1_off_IX_IY_d , "LD L,RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::RES_1_off_IX_IY_d      , "RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_1_off_IX_IY_d , "LD A,RES 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_2_off_IX_IY_d , "LD B,RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_2_off_IX_IY_d , "LD C,RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_2_off_IX_IY_d , "LD D,RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_2_off_IX_IY_d , "LD E,RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_2_off_IX_IY_d , "LD H,RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_2_off_IX_IY_d , "LD L,RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::RES_2_off_IX_IY_d      , "RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_2_off_IX_IY_d , "LD A,RES 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_3_off_IX_IY_d , "LD B,RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_3_off_IX_IY_d , "LD C,RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_3_off_IX_IY_d , "LD D,RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_3_off_IX_IY_d , "LD E,RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_3_off_IX_IY_d , "LD H,RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_3_off_IX_IY_d , "LD L,RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::RES_3_off_IX_IY_d      , "RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_3_off_IX_IY_d , "LD A,RES 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_4_off_IX_IY_d , "LD B,RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_4_off_IX_IY_d , "LD C,RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_4_off_IX_IY_d , "LD D,RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_4_off_IX_IY_d , "LD E,RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_4_off_IX_IY_d , "LD H,RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_4_off_IX_IY_d , "LD L,RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::RES_4_off_IX_IY_d      , "RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_4_off_IX_IY_d , "LD A,RES 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_5_off_IX_IY_d , "LD B,RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_5_off_IX_IY_d , "LD C,RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_5_off_IX_IY_d , "LD D,RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_5_off_IX_IY_d , "LD E,RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_5_off_IX_IY_d , "LD H,RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_5_off_IX_IY_d , "LD L,RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::RES_5_off_IX_IY_d      , "RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_5_off_IX_IY_d , "LD A,RES 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_6_off_IX_IY_d , "LD B,RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_6_off_IX_IY_d , "LD C,RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_6_off_IX_IY_d , "LD D,RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_6_off_IX_IY_d , "LD E,RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_6_off_IX_IY_d , "LD H,RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_6_off_IX_IY_d , "LD L,RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::RES_6_off_IX_IY_d      , "RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_6_off_IX_IY_d , "LD A,RES 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_RES_7_off_IX_IY_d , "LD B,RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_RES_7_off_IX_IY_d , "LD C,RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_RES_7_off_IX_IY_d , "LD D,RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_RES_7_off_IX_IY_d , "LD E,RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_RES_7_off_IX_IY_d , "LD H,RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_RES_7_off_IX_IY_d , "LD L,RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::RES_7_off_IX_IY_d      , "RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_RES_7_off_IX_IY_d , "LD A,RES 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_0_off_IX_IY_d , "LD B,SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_0_off_IX_IY_d , "LD C,SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_0_off_IX_IY_d , "LD D,SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_0_off_IX_IY_d , "LD E,SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_0_off_IX_IY_d , "LD H,SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_0_off_IX_IY_d , "LD L,SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::SET_0_off_IX_IY_d      , "SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_0_off_IX_IY_d , "LD A,SET 0,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_1_off_IX_IY_d , "LD B,SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_1_off_IX_IY_d , "LD C,SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_1_off_IX_IY_d , "LD D,SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_1_off_IX_IY_d , "LD E,SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_1_off_IX_IY_d , "LD H,SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_1_off_IX_IY_d , "LD L,SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::SET_1_off_IX_IY_d      , "SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_1_off_IX_IY_d , "LD A,SET 1,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_2_off_IX_IY_d , "LD B,SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_2_off_IX_IY_d , "LD C,SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_2_off_IX_IY_d , "LD D,SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_2_off_IX_IY_d , "LD E,SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_2_off_IX_IY_d , "LD H,SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_2_off_IX_IY_d , "LD L,SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::SET_2_off_IX_IY_d      , "SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_2_off_IX_IY_d , "LD A,SET 2,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_3_off_IX_IY_d , "LD B,SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_3_off_IX_IY_d , "LD C,SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_3_off_IX_IY_d , "LD D,SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_3_off_IX_IY_d , "LD E,SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_3_off_IX_IY_d , "LD H,SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_3_off_IX_IY_d , "LD L,SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::SET_3_off_IX_IY_d      , "SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_3_off_IX_IY_d , "LD A,SET 3,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_4_off_IX_IY_d , "LD B,SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_4_off_IX_IY_d , "LD C,SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_4_off_IX_IY_d , "LD D,SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_4_off_IX_IY_d , "LD E,SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_4_off_IX_IY_d , "LD H,SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_4_off_IX_IY_d , "LD L,SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::SET_4_off_IX_IY_d      , "SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_4_off_IX_IY_d , "LD A,SET 4,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_5_off_IX_IY_d , "LD B,SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_5_off_IX_IY_d , "LD C,SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_5_off_IX_IY_d , "LD D,SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_5_off_IX_IY_d , "LD E,SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_5_off_IX_IY_d , "LD H,SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_5_off_IX_IY_d , "LD L,SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::SET_5_off_IX_IY_d      , "SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_5_off_IX_IY_d , "LD A,SET 5,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_6_off_IX_IY_d , "LD B,SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_6_off_IX_IY_d , "LD C,SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_6_off_IX_IY_d , "LD D,SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_6_off_IX_IY_d , "LD E,SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_6_off_IX_IY_d , "LD H,SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_6_off_IX_IY_d , "LD L,SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::SET_6_off_IX_IY_d      , "SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_6_off_IX_IY_d , "LD A,SET 6,(IX+0%02Xh)" },
	{ &CZ80Core::LD_B_SET_7_off_IX_IY_d , "LD B,SET 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_C_SET_7_off_IX_IY_d , "LD C,SET 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_D_SET_7_off_IX_IY_d , "LD D,SET 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_E_SET_7_off_IX_IY_d , "LD E,SET 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_H_SET_7_off_IX_IY_d , "LD H,SET 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_L_SET_7_off_IX_IY_d , "LD L,SET 7,(IX+0%02Xh)" },
	{ &CZ80Core::SET_7_off_IX_IY_d      , "SET 7,(IX+0%02Xh)" },
	{ &CZ80Core::LD_A_SET_7_off_IX_IY_d , "LD A,SET 7,(IX+0%02Xh)" }
}};


CZ80Core::Z80OpcodeTable CZ80Core::Main_Opcodes = {
	{
		{ &CZ80Core::NOP                 , "NOP"              },
		{ &CZ80Core::LD_BC_nn            , "LD BC,0%04Xh"     },
		{ &CZ80Core::LD_off_BC_A         , "LD (BC),A"        },
		{ &CZ80Core::INC_BC              , "INC BC"           },
		{ &CZ80Core::INC_B               , "INC B"            },
		{ &CZ80Core::DEC_B               , "DEC B"            },
		{ &CZ80Core::LD_B_n              , "LD B,0%02Xh"      },
		{ &CZ80Core::RLCA                , "RLCA"             },
		{ &CZ80Core::EX_AF_AF_           , "EX AF,AF'"        },
		{ &CZ80Core::ADD_HL_BC           , "ADD HL,BC"        },
		{ &CZ80Core::LD_A_off_BC         , "LD A,(BC)"        },
		{ &CZ80Core::DEC_BC              , "DEC BC"           },
		{ &CZ80Core::INC_C               , "INC C"            },
		{ &CZ80Core::DEC_C               , "DEC C"            },
		{ &CZ80Core::LD_C_n              , "LD C,0%02Xh"      },
		{ &CZ80Core::RRCA                , "RRCA"             },
		{ &CZ80Core::DJNZ_off_PC_e       , "DJNZ (PC+%d)"     },
		{ &CZ80Core::LD_DE_nn            , "LD DE,0%04Xh"     },
		{ &CZ80Core::LD_off_DE_A         , "LD (DE),A"        },
		{ &CZ80Core::INC_DE              , "INC DE"           },
		{ &CZ80Core::INC_D               , "INC D"            },
		{ &CZ80Core::DEC_D               , "DEC D"            },
		{ &CZ80Core::LD_D_n              , "LD D,0%02Xh"      },
		{ &CZ80Core::RLA                 , "RLA"              },
		{ &CZ80Core::JR_off_PC_e         , "JR (PC+%d)"       },
		{ &CZ80Core::ADD_HL_DE           , "ADD HL,DE"        },
		{ &CZ80Core::LD_A_off_DE         , "LD A,(DE)"        },
		{ &CZ80Core::DEC_DE              , "DEC DE"           },
		{ &CZ80Core::INC_E               , "INC E"            },
		{ &CZ80Core::DEC_E               , "DEC E"            },
		{ &CZ80Core::LD_E_n              , "LD E,0%02Xh"      },
		{ &CZ80Core::RRA                 , "RRA"              },
		{ &CZ80Core::JR_NZ_off_PC_e      , "JR NZ,(PC+%d)"    },
		{ &CZ80Core::LD_HL_nn            , "LD HL,0%04Xh"     },
		{ &CZ80Core::LD_off_nn_HL        , "LD (0%04Xh),HL"   },
		{ &CZ80Core::INC_HL              , "INC HL"           },
		{ &CZ80Core::INC_H               , "INC H"            },
		{ &CZ80Core::DEC_H               , "DEC H"            },
		{ &CZ80Core::LD_H_n              , "LD H,0%02Xh"      },
		{ &CZ80Core::DAA                 , "DAA"              },
		{ &CZ80Core::JR_Z_off_PC_e       , "JR Z,(PC+%d)"     },
		{ &CZ80Core::ADD_HL_HL           , "ADD HL,HL"        },
		{ &CZ80Core::LD_HL_off_nn        , "LD HL,(0%04Xh)"   },
		{ &CZ80Core::DEC_HL              , "DEC HL"           },
		{ &CZ80Core::INC_L               , "INC L"            },
		{ &CZ80Core::DEC_L               , "DEC L"            },
		{ &CZ80Core::LD_L_n              , "LD L,0%02Xh"      },
		{ &CZ80Core::CPL                 , "CPL"              },
		{ &CZ80Core::JR_NC_off_PC_e      , "JR NC,(PC+%d)"    },
		{ &CZ80Core::LD_SP_nn            , "LD SP,0%04Xh"     },
		{ &CZ80Core::LD_off_nn_A         , "LD (0%04Xh),A"    },
		{ &CZ80Core::INC_SP              , "INC SP"           },
		{ &CZ80Core::INC_off_HL          , "INC (HL)"         },
		{ &CZ80Core::DEC_off_HL          , "DEC (HL)"         },
		{ &CZ80Core::LD_off_HL_n         , "LD (HL),0%02Xh"   },
		{ &CZ80Core::SCF                 , "SCF"              },
		{ &CZ80Core::JR_C_off_PC_e       , "JR C,(PC+%d)"     },
		{ &CZ80Core::ADD_HL_SP           , "ADD HL,SP"        },
		{ &CZ80Core::LD_A_off_nn         , "LD A,(0%04Xh)"    },
		{ &CZ80Core::DEC_SP              , "DEC SP"           },
		{ &CZ80Core::INC_A               , "INC A"            },
		{ &CZ80Core::DEC_A               , "DEC A"            },
		{ &CZ80Core::LD_A_n              , "LD A,0%02Xh"      },
		{ &CZ80Core::CCF                 , "CCF"              },
		{ &CZ80Core::LD_B_B              , "LD B,B"           },
		{ &CZ80Core::LD_B_C              , "LD B,C"           },
		{ &CZ80Core::LD_B_D              , "LD B,D"           },
		{ &CZ80Core::LD_B_E              , "LD B,E"           },
		{ &CZ80Core::LD_B_H              , "LD B,H"           },
		{ &CZ80Core::LD_B_L              , "LD B,L"           },
		{ &CZ80Core::LD_B_off_HL         , "LD B,(HL)"        },
		{ &CZ80Core::LD_B_A              , "LD B,A"           },
		{ &CZ80Core::LD_C_B              , "LD C,B"           },
		{ &CZ80Core::LD_C_C              , "LD C,C"           },
		{ &CZ80Core::LD_C_D              , "LD C,D"           },
		{ &CZ80Core::LD_C_E              , "LD C,E"           },
		{ &CZ80Core::LD_C_H              , "LD C,H"           },
		{ &CZ80Core::LD_C_L              , "LD C,L"           },
		{ &CZ80Core::LD_C_off_HL         , "LD C,(HL)"        },
		{ &CZ80Core::LD_C_A              , "LD C,A"           },
		{ &CZ80Core::LD_D_B              , "LD D,B"           },
		{ &CZ80Core::LD_D_C              , "LD D,C"           },
		{ &CZ80Core::LD_D_D              , "LD D,D"           },
		{ &CZ80Core::LD_D_E              , "LD D,E"           },
		{ &CZ80Core::LD_D_H              , "LD D,H"           },
		{ &CZ80Core::LD_D_L              , "LD D,L"           },
		{ &CZ80Core::LD_D_off_HL         , "LD D,(HL)"        },
		{ &CZ80Core::LD_D_A              , "LD D,A"           },
		{ &CZ80Core::LD_E_B              , "LD E,B"           },
		{ &CZ80Core::LD_E_C              , "LD E,C"           },
		{ &CZ80Core::LD_E_D              , "LD E,D"           },
		{ &CZ80Core::LD_E_E              , "LD E,E"           },
		{ &CZ80Core::LD_E_H              , "LD E,H"           },
		{ &CZ80Core::LD_E_L              , "LD E,L"           },
		{ &CZ80Core::LD_E_off_HL         , "LD E,(HL)"        },
		{ &CZ80Core::LD_E_A              , "LD E,A"           },
		{ &CZ80Core::LD_H_B              , "LD H,B"           },
		{ &CZ80Core::LD_H_C              , "LD H,C"           },
		{ &CZ80Core::LD_H_D              , "LD H,D"           },
		{ &CZ80Core::LD_H_E              , "LD H,E"           },
		{ &CZ80Core::LD_H_H              , "LD H,H"           },
		{ &CZ80Core::LD_H_L              , "LD H,L"           },
		{ &CZ80Core::LD_H_off_HL         , "LD H,(HL)"        },
		{ &CZ80Core::LD_H_A              , "LD H,A"           },
		{ &CZ80Core::LD_L_B              , "LD L,B"           },
		{ &CZ80Core::LD_L_C              , "LD L,C"           },
		{ &CZ80Core::LD_L_D              , "LD L,D"           },
		{ &CZ80Core::LD_L_E              , "LD L,E"           },
		{ &CZ80Core::LD_L_H              , "LD L,H"           },
		{ &CZ80Core::LD_L_L              , "LD L,L"           },
		{ &CZ80Core::LD_L_off_HL         , "LD L,(HL)"        },
		{ &CZ80Core::LD_L_A              , "LD L,A"           },
		{ &CZ80Core::LD_off_HL_B         , "LD (HL),B"        },
		{ &CZ80Core::LD_off_HL_C         , "LD (HL),C"        },
		{ &CZ80Core::LD_off_HL_D         , "LD (HL),D"        },
		{ &CZ80Core::LD_off_HL_E         , "LD (HL),E"        },
		{ &CZ80Core::LD_off_HL_H         , "LD (HL),H"        },
		{ &CZ80Core::LD_off_HL_L         , "LD (HL),L"        },
		{ &CZ80Core::HALT                , "HALT"             },
		{ &CZ80Core::LD_off_HL_A         , "LD (HL),A"        },
		{ &CZ80Core::LD_A_B              , "LD A,B"           },
		{ &CZ80Core::LD_A_C              , "LD A,C"           },
		{ &CZ80Core::LD_A_D              , "LD A,D"           },
		{ &CZ80Core::LD_A_E              , "LD A,E"           },
		{ &CZ80Core::LD_A_H              , "LD A,H"           },
		{ &CZ80Core::LD_A_L              , "LD A,L"           },
		{ &CZ80Core::LD_A_off_HL         , "LD A,(HL)"        },
		{ &CZ80Core::LD_A_A              , "LD A,A"           },
		{ &CZ80Core::ADD_A_B             , "ADD A,B"          },
		{ &CZ80Core::ADD_A_C             , "ADD A,C"          },
		{ &CZ80Core::ADD_A_D             , "ADD A,D"          },
		{ &CZ80Core::ADD_A_E             , "ADD A,E"          },
		{ &CZ80Core::ADD_A_H             , "ADD A,H"          },
		{ &CZ80Core::ADD_A_L             , "ADD A,L"          },
		{ &CZ80Core::ADD_A_off_HL        , "ADD A,(HL)"       },
		{ &CZ80Core::ADD_A_A             , "ADD A,A"          },
		{ &CZ80Core::ADC_A_B             , "ADC A,B"          },
		{ &CZ80Core::ADC_A_C             , "ADC A,C"          },
		{ &CZ80Core::ADC_A_D             , "ADC A,D"          },
		{ &CZ80Core::ADC_A_E             , "ADC A,E"          },
		{ &CZ80Core::ADC_A_H             , "ADC A,H"          },
		{ &CZ80Core::ADC_A_L             , "ADC A,L"          },
		{ &CZ80Core::ADC_A_off_HL        , "ADC A,(HL)"       },
		{ &CZ80Core::ADC_A_A             , "ADC A,A"          },
		{ &CZ80Core::SUB_A_B             , "SUB A,B"          },
		{ &CZ80Core::SUB_A_C             , "SUB A,C"          },
		{ &CZ80Core::SUB_A_D             , "SUB A,D"          },
		{ &CZ80Core::SUB_A_E             , "SUB A,E"          },
		{ &CZ80Core::SUB_A_H             , "SUB A,H"          },
		{ &CZ80Core::SUB_A_L             , "SUB A,L"          },
		{ &CZ80Core::SUB_A_off_HL        , "SUB A,(HL)"       },
		{ &CZ80Core::SUB_A_A             , "SUB A,A"          },
		{ &CZ80Core::SBC_A_B             , "SBC A,B"          },
		{ &CZ80Core::SBC_A_C             , "SBC A,C"          },
		{ &CZ80Core::SBC_A_D             , "SBC A,D"          },
		{ &CZ80Core::SBC_A_E             , "SBC A,E"          },
		{ &CZ80Core::SBC_A_H             , "SBC A,H"          },
		{ &CZ80Core::SBC_A_L             , "SBC A,L"          },
		{ &CZ80Core::SBC_A_off_HL        , "SBC A,(HL)"       },
		{ &CZ80Core::SBC_A_A             , "SBC A,A"          },
		{ &CZ80Core::AND_B               , "AND B"            },
		{ &CZ80Core::AND_C               , "AND C"            },
		{ &CZ80Core::AND_D               , "AND D"            },
		{ &CZ80Core::AND_E               , "AND E"            },
		{ &CZ80Core::AND_H               , "AND H"            },
		{ &CZ80Core::AND_L               , "AND L"            },
		{ &CZ80Core::AND_off_HL          , "AND (HL)"         },
		{ &CZ80Core::AND_A               , "AND A"            },
		{ &CZ80Core::XOR_B               , "XOR B"            },
		{ &CZ80Core::XOR_C               , "XOR C"            },
		{ &CZ80Core::XOR_D               , "XOR D"            },
		{ &CZ80Core::XOR_E               , "XOR E"            },
		{ &CZ80Core::XOR_H               , "XOR H"            },
		{ &CZ80Core::XOR_L               , "XOR L"            },
		{ &CZ80Core::XOR_off_HL          , "XOR (HL)"         },
		{ &CZ80Core::XOR_A               , "XOR A"            },
		{ &CZ80Core::OR_B                , "OR B"             },
		{ &CZ80Core::OR_C                , "OR C"             },
		{ &CZ80Core::OR_D                , "OR D"             },
		{ &CZ80Core::OR_E                , "OR E"             },
		{ &CZ80Core::OR_H                , "OR H"             },
		{ &CZ80Core::OR_L                , "OR L"             },
		{ &CZ80Core::OR_off_HL           , "OR (HL)"          },
		{ &CZ80Core::OR_A                , "OR A"             },
		{ &CZ80Core::CP_B                , "CP B"             },
		{ &CZ80Core::CP_C                , "CP C"             },
		{ &CZ80Core::CP_D                , "CP D"             },
		{ &CZ80Core::CP_E                , "CP E"             },
		{ &CZ80Core::CP_H                , "CP H"             },
		{ &CZ80Core::CP_L                , "CP L"             },
		{ &CZ80Core::CP_off_HL           , "CP (HL)"          },
		{ &CZ80Core::CP_A                , "CP A"             },
		{ &CZ80Core::RET_NZ              , "RET NZ"           },
		{ &CZ80Core::POP_BC              , "POP BC"           },
		{ &CZ80Core::JP_NZ_off_nn        , "JP NZ,(0%04Xh)"   },
		{ &CZ80Core::JP_off_nn           , "JP (0%04Xh)"      },
		{ &CZ80Core::CALL_NZ_off_nn      , "CALL NZ,(0%04Xh)" },
		{ &CZ80Core::PUSH_BC             , "PUSH BC"          },
		{ &CZ80Core::ADD_A_n             , "ADD A,0%02Xh"     },
		{ &CZ80Core::RST_0H              , "RST 0H"           },
		{ &CZ80Core::RET_Z               , "RET Z"            },
		{ &CZ80Core::RET                 , "RET"              },
		{ &CZ80Core::JP_Z_off_nn         , "JP Z,(0%04Xh)"    },
		{ NULL							 , NULL               },
		{ &CZ80Core::CALL_Z_off_nn       , "CALL Z,(0%04Xh)"  },
		{ &CZ80Core::CALL_off_nn         , "CALL (0%04Xh)"    },
		{ &CZ80Core::ADC_A_n             , "ADC A,0%02Xh"     },
		{ &CZ80Core::RST_8H              , "RST 8H"           },
		{ &CZ80Core::RET_NC              , "RET NC"           },
		{ &CZ80Core::POP_DE              , "POP DE"           },
		{ &CZ80Core::JP_NC_off_nn        , "JP NC,(0%04Xh)"   },
		{ &CZ80Core::OUT_off_n_A         , "OUT (0%02Xh),A"   },
		{ &CZ80Core::CALL_NC_off_nn      , "CALL NC,(0%04Xh)" },
		{ &CZ80Core::PUSH_DE             , "PUSH DE"          },
		{ &CZ80Core::SUB_A_n             , "SUB A,0%02Xh"     },
		{ &CZ80Core::RST_10H             , "RST 10H"          },
		{ &CZ80Core::RET_C               , "RET C"            },
		{ &CZ80Core::EXX                 , "EXX"              },
		{ &CZ80Core::JP_C_off_nn         , "JP C,(0%04Xh)"    },
		{ &CZ80Core::IN_A_off_n          , "IN A,(0%02Xh)"    },
		{ &CZ80Core::CALL_C_off_nn       , "CALL C,(0%04Xh)"  },
		{ NULL							 , NULL               },
		{ &CZ80Core::SBC_A_n             , "SBC A,0%02Xh"     },
		{ &CZ80Core::RST_18H             , "RST 18H"          },
		{ &CZ80Core::RET_PO              , "RET PO"           },
		{ &CZ80Core::POP_HL              , "POP HL"           },
		{ &CZ80Core::JP_PO_off_nn        , "JP PO,(0%04Xh)"   },
		{ &CZ80Core::EX_off_SP_HL        , "EX (SP),HL"       },
		{ &CZ80Core::CALL_PO_off_nn      , "CALL PO,(0%04Xh)" },
		{ &CZ80Core::PUSH_HL             , "PUSH HL"          },
		{ &CZ80Core::AND_n               , "AND 0%02Xh"       },
		{ &CZ80Core::RST_20H             , "RST 20H"          },
		{ &CZ80Core::RET_PE              , "RET PE"           },
		{ &CZ80Core::JP_off_HL           , "JP (HL)"          },
		{ &CZ80Core::JP_PE_off_nn        , "JP PE,(0%04Xh)"   },
		{ &CZ80Core::EX_DE_HL            , "EX DE,HL"         },
		{ &CZ80Core::CALL_PE_off_nn      , "CALL PE,(0%04Xh)" },
		{ NULL							 , NULL               },
		{ &CZ80Core::XOR_n               , "XOR 0%02Xh"       },
		{ &CZ80Core::RST_28H             , "RST 28H"          },
		{ &CZ80Core::RET_P               , "RET P"            },
		{ &CZ80Core::POP_AF              , "POP AF"           },
		{ &CZ80Core::JP_P_off_nn         , "JP P,(0%04Xh)"    },
		{ &CZ80Core::DI                  , "DI"               },
		{ &CZ80Core::CALL_P_off_nn       , "CALL P,(0%04Xh)"  },
		{ &CZ80Core::PUSH_AF             , "PUSH AF"          },
		{ &CZ80Core::OR_n                , "OR 0%02Xh"        },
		{ &CZ80Core::RST_30H             , "RST 30H"          },
		{ &CZ80Core::RET_M               , "RET M"            },
		{ &CZ80Core::LD_SP_HL            , "LD SP,HL"         },
		{ &CZ80Core::JP_M_off_nn         , "JP M,(0%04Xh)"    },
		{ &CZ80Core::EI                  , "EI"               },
		{ &CZ80Core::CALL_M_off_nn       , "CALL M,(0%04Xh)"  },
		{ NULL							 , NULL				  },
		{ &CZ80Core::CP_n                , "CP 0%02Xh"        },
		{ &CZ80Core::RST_38H             , "RST 38H"          }
	}
};
